name: MSBuild
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2



    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Releases
        path: 'miniapp/miniapp.Packaging/**/*.apk'
